#!/bin/bash

# NodAI Deployment Script

echo "🚀 NodAI Deployment with Docker & Traefik"
echo "========================================="

# Check if Docker is running
if ! docker info > /dev/null 2>&1; then
    echo "❌ Docker is not running. Please start Docker first."
    exit 1
fi

# Create Traefik network if it doesn't exist
if ! docker network ls | grep -q traefik; then
    echo "📡 Creating Traefik network..."
    docker network create traefik
fi

# Check if environment variables are set
if [ -z "$GEMINI_API_KEY" ]; then
    echo "⚠️  Warning: GEMINI_API_KEY environment variable is not set"
    echo "   Make sure to set it before running the application"
fi

# Build and start services
echo "🔨 Building and starting services..."
docker compose up -d --build

echo ""
echo "✅ Deployment complete!"
echo ""
echo "🌐 Your application will be available at:"
echo "   • https://nodai.app (production)"
echo "   • https://traefik.nodai.app (Traefik dashboard)"
echo ""
echo "📋 Useful commands:"
echo "   • docker-compose logs -f nodai-web    # View app logs"
echo "   • docker-compose logs -f traefik      # View Traefik logs"
echo "   • docker-compose down                 # Stop services"
echo "   • docker-compose up -d --build        # Rebuild and restart"
echo ""
echo "🔒 SSL certificates will be automatically generated by Let's Encrypt"
echo "   First request might take a few minutes while certificates are issued"
